# Generated by Django 4.1.6 on 2023-02-08 16:26

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_created', models.DateTimeField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Budget', models.IntegerField()),
                ('Actual_cost', models.IntegerField()),
                ('Expected_revenue', models.IntegerField()),
                ('Campaign_objective', models.IntegerField()),
                ('Campaign_description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Contact_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Last_Name', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Email_Address', models.EmailField(max_length=50)),
                ('Company_Name', models.CharField(max_length=50)),
                ('Address_1', models.CharField(max_length=250)),
                ('Birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designations', models.CharField(choices=[('Customer Service Executive', 'Customer Service Executive'), ('Human Resources', 'Human Resources'), ('Sales Resource', 'Sales Resource'), ('Operations Officer', 'Operations Officer'), ('Marketing Officer', 'Marketing Officer'), ('Management', 'Management')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Records',
            fields=[
                ('Employee_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Employment_date', models.DateField()),
                ('Resumption_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('Tracking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Escalation', models.CharField(choices=[('MISDECLARATION', 'Misdeclaration'), ('THEFT', 'Theft'), ('Delays', 'Delays'), ('Specify Others', 'Specify Others')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tdolcrm.contact')),
                ('Leads', models.CharField(choices=[('Coldcall', 'Coldcall'), ('Campaign', 'Campaign'), ('Email', 'Email'), ('Word of Mouth', 'Word of Mouth'), ('Website', 'Website'), ('Tradeshow', 'Tradeshow'), ('Direct mail', 'Direct mail'), ('Employee referral', 'Employee referral'), ('Self generated', 'Self generated'), ('Existing customer', 'Existing customer'), ('Other', 'Other')], max_length=25)),
            ],
            bases=('tdolcrm.contact',),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tdolcrm.contact')),
                ('Nature_of_Business', models.CharField(max_length=50)),
                ('Nature_of_Shipment', models.CharField(max_length=50)),
                ('Pickup_location', models.CharField(max_length=17)),
                ('NoOfPackages_Monthly', models.IntegerField()),
                ('Monthly_revenue', models.IntegerField()),
            ],
            bases=('tdolcrm.contact',),
        ),
        migrations.CreateModel(
            name='Sales_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Human_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Service_Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_processed', models.DateTimeField()),
                ('Case_description', models.CharField(max_length=500)),
                ('Case_Categories', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='tdolcrm.shipment')),
                ('Shipments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_name', models.CharField(max_length=20)),
                ('Date_created1', models.DateField()),
                ('Start_date1', models.DateField()),
                ('End_date1', models.DateField()),
                ('Activity_description', models.TextField(max_length=300)),
                ('Campaign_Activities', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tdolcrm.campaign')),
                ('Employee_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('prospect_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tdolcrm.prospect')),
                ('Customer_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Consignee_Name', models.CharField(max_length=50)),
                ('Consignee_Company', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('No_of_packages_monthly', models.IntegerField()),
            ],
            bases=('tdolcrm.prospect',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Invoice_date', models.DateTimeField(auto_now_add=True)),
                ('Shipment_origin', models.CharField(max_length=40)),
                ('No_of_packages1', models.IntegerField()),
                ('Total_Billable_weight', models.IntegerField()),
                ('Insurances', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('Packaging_fee', models.IntegerField()),
                ('Freight_cost', models.IntegerField()),
                ('Total_shipment_cost', models.IntegerField()),
                ('Tracking_numbers', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tdolcrm.shipment')),
                ('Consignee_Name_inv', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tdolcrm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches_loc', models.CharField(choices=[('Ikeja', 'Ikeja'), ('Gbagada', 'Gbagada'), ('Surulere', 'Surulere')], max_length=8)),
                ('branch_employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='tdolcrm.employee_records')),
                ('employee_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_order',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tdolcrm.customer')),
                ('Consignee_telephone', models.IntegerField()),
                ('No_of_packages', models.IntegerField()),
                ('Dimensional_weight', models.IntegerField()),
                ('Dimensional_height', models.IntegerField()),
                ('Item_description', models.TextField(max_length=250)),
                ('Customer_signature', models.CharField(max_length=250)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='tdolcrm.customer')),
            ],
            bases=('tdolcrm.customer',),
        ),
        migrations.AddField(
            model_name='shipment',
            name='Shipmentorder1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='tdolcrm.shipment_order'),
        ),
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_label', models.CharField(max_length=30)),
                ('pictures', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('AMOUNT_OF_QTY_SHIPPED', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')])),
                ('shipmentorder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tdolcrm.shipment_order')),
            ],
        ),
    ]
