# Generated by Django 4.1.6 on 2023-02-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdolcrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='Activity_name',
            field=models.CharField(max_length=100),
        ),
    ]
