# Generated by Django 4.1.6 on 2023-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdolcrm', '0002_alter_activities_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_records',
            name='Employee_ID',
            field=models.IntegerField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
